# Generated by Django 4.2.4 on 2023-09-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(blank=True, null=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=54, null=True)),
                ('contrasena', models.TextField()),
                ('email', models.EmailField(max_length=10, unique=True)),
                ('nivel_cuenta', models.IntegerField(blank=True, null=True)),
                ('fecha_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=54, null=True)),
                ('apellido_p', models.CharField(blank=True, max_length=54, null=True)),
                ('apellido_m', models.CharField(blank=True, max_length=54, null=True)),
                ('telefono', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('genero', models.CharField(blank=True, max_length=54, null=True)),
                ('nombre_usu', models.CharField(blank=True, max_length=54, null=True, unique=True)),
                ('razon_social', models.CharField(blank=True, default='N/A', max_length=54, null=True)),
                ('rut_empr', models.IntegerField(default=0)),
                ('dv_empr', models.CharField(default='N/A', max_length=1)),
                ('direccion_empr', models.CharField(default='N/A', max_length=54)),
                ('ultimo_inicio', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last login')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
