# Generated by Django 4.2.4 on 2023-09-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(blank=True, null=True)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('contrasena', models.TextField()),
                ('email', models.EmailField(max_length=10, unique=True)),
                ('nivel_cuenta', models.IntegerField(blank=True, null=True)),
                ('fecha_nac', models.DateField()),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=54, null=True)),
                ('apellido_p', models.CharField(blank=True, max_length=54, null=True)),
                ('apellido_m', models.CharField(blank=True, max_length=54, null=True)),
                ('telefono', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('genero', models.CharField(blank=True, max_length=54, null=True)),
                ('nombre_usu', models.CharField(blank=True, max_length=54, null=True, unique=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
