# Generated by Django 4.2.4 on 2023-09-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_curriculums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='ultimo_inicio',
            new_name='last_login',
        ),
    ]
